### ISSUE TITLE
Calling GraphQL over GET results in an error

### ISSUE THREAD

**Issue by jopmiddelkamp** [kamilkisiela/apollo-angular#1470]
**Intended outcome:**

I've added the package to the Angular project and set the `uri` to the local GraphQL endpoint. (the method I've added later)
![image](https://user-images.githubusercontent.com/1774351/75442081-47ebff00-5991-11ea-96af-beb586952c65.png)

Then created a query to get all the data from the GraphQL endpoint.
![image](https://user-images.githubusercontent.com/1774351/75442259-a913d280-5991-11ea-8ff1-965c16a7d55d.png)

The data came back without any problems. Then I've added the `method: 'GET'` to the 
![image](https://user-images.githubusercontent.com/1774351/75442081-47ebff00-5991-11ea-96af-beb586952c65.png)

Getting result back from the `httpLink.create(` method parameters. Now I would expect the result to return as before only now using `GET` instead of `POST`. But instead if gives back the error in the next paragraph.

**Actual outcome:**

![image](https://user-images.githubusercontent.com/1774351/75442962-107e5200-5993-11ea-8f7d-59a2bd868da8.png)

```
{
  "errors":[
    {
      "message":"Cannot read property 'operation' of undefined",
      "extensions":{
        "code":"INTERNAL_SERVER_ERROR",
        "exception":{
          "stacktrace":[
            "TypeError: Cannot read property 'operation' of undefined",
            "    at Object.didResolveOperation (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/runHttpQuery.js:253:64)",
            "    at /Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/utils/dispatcher.js:21:35",
            "    at Array.map (<anonymous>)",
            "    at Dispatcher.<anonymous> (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/utils/dispatcher.js:18:51)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/utils/dispatcher.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/utils/dispatcher.js:4:12)",
            "    at Dispatcher.invokeHookAsync (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/utils/dispatcher.js:17:16)",
            "    at Object.<anonymous> (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/requestPipeline.js:142:34)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/xxx/Projects/reproduction/reproduction-aags/strapi-app/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ]
}
```

**How to reproduce the issue:**

See the repp: [https://github.com/jopmiddelkamp/reproduction-aags](https://github.com/jopmiddelkamp/reproduction-aags)

**Versions**

```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "apollo-angular": "^1.8.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-link": "^1.2.11",
    "apollo-client": "^2.6.0",
    "apollo-cache-inmemory": "^1.6.0",
    "graphql-tag": "^2.10.0",
    "graphql": "^14.5.0"
  },
```

**Comment by fetis** [comment]
I'm not sure that's an issue with `apollo-angular`, your backend should support GET method for graphql queries as I can see from the screenshot it doesn't (400 Bad request)

Generally, GraphQL was designed to work other POST, not other GET methods

**Comment by fetis** [comment]
closing due to inactivity
