### ISSUE TITLE
Migration from 1.10.0 to 2 fails because it could not parse tsconfig.base.json

### ISSUE THREAD

**Issue by muuvmuuv** [kamilkisiela/apollo-angular#1548]
**Describe the bug**

```
❯ ng update apollo-angular --migrate-only --from 1.10.0
Using package manager: 'npm'
Collecting installed dependencies...
Found 98 dependencies.
** Executing migrations of package 'apollo-angular' **

❯ Update to Apollo Angular 2 and Apollo Client 3
✖ Migration failed: Couldn't parse tsconfig.base.json!
  See "/private/var/folders/yz/pntm5xh11mjb3ckzvf10ql180000gn/T/ng-a1WVn4/angular-errors.log" for further details.
```

```
[error] Error: Couldn't parse tsconfig.base.json!
    at Object.getJsonFile (PROJECT_ROOT/node_modules/apollo-angular/schematics/utils/file.js:29:15)
    at PROJECT_ROOT/node_modules/apollo-angular/schematics/migrations/v2.js:79:42
    at Generator.next (<anonymous>)
    at PROJECT_ROOT/node_modules/apollo-angular/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (PROJECT_ROOT/node_modules/apollo-angular/node_modules/tslib/tslib.js:110:16)
    at migrateTsConfig (PROJECT_ROOT/node_modules/apollo-angular/schematics/migrations/v2.js:69:20)
    at MergeMapSubscriber.project (PROJECT_ROOT/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:95:26)
    at InnerSubscriber._next (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:95:26)
    at InnerSubscriber._next (PROJECT_ROOT/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
```

**To Reproduce**

**Expected behavior**

**Environment:**

- `@apollo/client`: 3.1.3
- `apollo-angular`: 2.0.3
- `graphql`: 15.3.0
- `@angular/core`: 10.0.10
- `@angular/cli`: 10.0.6
- `typescript`: 3.9.7

> Yes it is latest because I did `npm up` but now want to migrate manually.

**Additional context**

tsconfig.json
```
/*
  This is a "Solution Style" tsconfig.json file, and is used by editors and TypeScript’s language server to improve development experience.
  It is not intended to be used to perform a compilation.

  To learn more about this file see: https://angular.io/config/solution-tsconfig.
*/
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./cypress/tsconfig.json"
    },
    {
      "path": "./tsconfig.worker.json"
    }
  ]
}
``` 

tsconfig.base.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./out-tsc/dist",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": false,
    "strictNullChecks": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "module": "ES2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2015",
    "lib": [
      "ES2018",
      "DOM"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    // "strictTemplates": true // NOTE: https://github.com/angular/angular/issues/25963
  }
}
```

**Comment by kamilkisiela** [comment]
@muuvmuuv #1549 should fix it

**Comment by kamilkisiela** [comment]
`v2.0.4` should fix it, try again

**Comment by muuvmuuv** [comment]
Uhm... something went terribly wrong here:

Before:

```ts
import { Injectable } from '@angular/core'
import { Observable, empty } from 'rxjs'
import { map, catchError } from 'rxjs/operators'
import { Apollo, ApolloBase } from 'apollo-angular'
import { ApolloError } from '@apollo/client/core'
```

After:

```ts
iimport {Apollo, ApolloBase} from 'apollo-angular';
mport { Injectable } from '@angular/core'
import { Observable, empty } from 'rxjs'
import { map, catchError } from 'rxjs/operators'
iimport { ApolloError } from '@apollo/client/core'
```

It also removed all my comments from `tsconfig.base.json` and `graphql-tag` from `package.json`, why that? Also noticed that it downgrades `@apollo/client` and `graphql`.

**Comment by muuvmuuv** [comment]
If someone, like me, has already started migrating manually. It should just leaves those files as it and keep the version if it is higher than the version from the migration script. And it should really not remove comments. But in the end it was successful. 😄

**Comment by kamilkisiela** [comment]
`graphql-tag` comes with `apollo-angular`. The migration script assumes it runs for the first time.

I accept PRs, too much work on my side this week to fix anything on `ng update`.

**Comment by kamilkisiela** [comment]
@muuvmuuv https://github.com/kamilkisiela/apollo-angular/commit/e25d4f8dae63ec1a1b7d9e03279e4e79639c7841

**Comment by fetis** [comment]
@muuvmuuv I think it was fixed. I did migration without problems recently. Can we close the issue?
