### ISSUE TITLE
Form data ID strings interpreted as Buffer at GraphQL backend

### ISSUE THREAD

**Issue by MilosStanic** [kamilkisiela/apollo-angular#1643]
**Describe the bug**

I have a component with a reactive form that I use to create or edit an entity in my data model. 
The form has two dropdowns and one material chip select where I select references to other objects in the database (MongoDB).
When I use the form to create a new entry, all works fine. 
But then, when I use the exact same form, with prepopulated data, to edit existing entry, and when I submit to backend, I am getting an error
`ID cannot represent value: <Buffer 5e 74 8d 4e 1e 1d 73 37 88 ba 50 f7>`
Stacktrace:
```
[
  "GraphQLError: ID cannot represent value: <Buffer 5e 74 8d 4e 1e 1d 73 37 88 ba 50 f7>",
  "    at GraphQLScalarType.serializeID [as serialize] (Z:\\digimet\\node_modules\\graphql\\type\\scalars.js:247:9)",
  "    at completeLeafValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:653:37)",
  "    at completeValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:578:12)",
  "    at completeValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:556:21)",
  "    at resolveField (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:472:19)",
  "    at executeFields (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:292:18)",
  "    at collectAndExecuteSubfields (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:748:10)",
  "    at completeObjectValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:738:10)",
  "    at completeValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:590:12)",
  "    at resolveField (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:472:19)",
  "    at executeFields (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:292:18)",
  "    at collectAndExecuteSubfields (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:748:10)",
  "    at completeObjectValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:738:10)",
  "    at completeValue (Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:590:12)",
  "    at Z:\\digimet\\node_modules\\graphql\\execution\\execute.js:469:16",
  "    at process._tickCallback (internal/process/next_tick.js:68:7)"
]
```
The actual value that is being sent is a normal string `5e748d4e1e1d733788ba50f7`. I've verified this both through console.log and by watching the query string and parameters in the Network tab of Chrome.
The error I am getting is non-fatal. The query executes, and the entry is updated in the MongoDB. It just returns this error with `200 OK` message.
There are error for all the ID strings that I am sending in a single request. The one quoted above is just one of them, they are all the same.

**Environment:**

- `@apollo/client`: ^3.0.0
- `apollo-angular`: ^2.2.0
- `graphql`: ^15.0.0
- `@angular/core`: ^11.1.1
- `@angular/cli`: ^11.1.2
- `typescript`: ^4.1.3

**Comment by MilosStanic** [comment]
Sorry, problem was in the backend. The update query was supposed to populate return model with related documents.
I found a solution here https://stackoverflow.com/a/63262199
