### ISSUE TITLE
Installation with "ng add" is failing for v3.0.0

### ISSUE THREAD

**Issue by enzeart** [kamilkisiela/apollo-angular#1760]
**Describe the bug**

Installation with "ng add" is failing for v3.0.0.

**To Reproduce**
ng new ui --routing=true --style=scss --skip-git
ng add --skip-confirmation apollo-angular --endpoint="/api/graphql"

**Expected behavior**

I expect the package to be installed and for the project to be updated according to the schematic logic.

**Environment:**
Some of the requested packages are missing after the attempted installation. Probably due to the failure.

@angular/cli@13.2.4 
@angular/core@13.2.3 
apollo-angular@3.0.0 
 typescript@4.5.5 

I've also tried this installation with Angular 12.2.14 and 12.2.16.

**Additional context**
[error] Error: Cannot find module '<redacted>/node_modules/apollo-angular/schematics/install'
Require stack:
- <redacted>/node_modules/@angular/cli/models/schematic-engine-host.js
- <redacted>/node_modules/@angular/cli/models/schematic-command.js
- <redacted>/node_modules/@angular/cli/commands/add-impl.js
- <redacted>/node_modules/@angular-devkit/schematics/tools/export-ref.js
-<redacted>/node_modules/@angular-devkit/schematics/tools/index.js
- <redacted>/node_modules/@angular/cli/utilities/json-schema.js
- <redacted>/node_modules/@angular/cli/models/command-runner.js
- <redacted>/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at SchematicEngineHost._resolveReferenceString (<redacted>/node_modules/@angular/cli/models/schematic-engine-host.js:57:39)
    at SchematicEngineHost.createSchematicDescription (<redacted>/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:181:34)
    at SchematicEngine.createSchematic (<redacted>/node_modules/@angular-devkit/schematics/src/engine/engine.js:228:38)
    at CollectionImpl.createSchematic (<redacted>/node_modules/@angular-devkit/schematics/src/engine/engine.js:80:29)
    at AddCommand.getSchematic (<redacted>/node_modules/@angular/cli/models/schematic-command.js:150:27)
    at AddCommand.runSchematic (<redacted>/node_modules/@angular/cli/models/schematic-command.js:336:32)
    at AddCommand.executeSchematic (<redacted>/node_modules/@angular/cli/commands/add-impl.js:263:31)
    at AddCommand.run <redacted>/node_modules/@angular/cli/commands/add-impl.js:208:21)

**Comment by LexanRed** [comment]
Same problem here, any update on this one?

**Comment by hexdecimal16** [comment]
yes same problem

**Comment by weeken88** [comment]
Same problem. Both using Angular 12 and 14.

**Comment by MikaStark** [comment]
ng update is failling too

**Comment by juane1000** [comment]
Same issue. Any update on this?

**Comment by foorschtbar** [comment]
Is there an update here? Just wanted to get started with Apollo 3 and Angular 13 - which is not an uncommon combination - and get exactly the same error :-(

**Comment by BlinkAC** [comment]
same error

**Comment by MikaStark** [comment]
The only solution is to manually install/update Apollo-angular (see readme file)

**Comment by kamilkisiela** [comment]
PR welcome

**Comment by kamilkisiela** [comment]
> PR welcome

`v3.0.1` is out, try it out and let me know if it works

**Comment by afkir01** [comment]
Just created a new app with Angular version 13.1.3 and apollo-angular version 3.0 and works perfect.
